name: build

on:
  push:
    branches:
      - master

env:
  REPO: ${{ github.repository }}
  REPO_URL: ${{ github.repositoryUrl }}
  RUNID: ${{ github.run_id }}
  RUNNR: ${{ github.run_number }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  PMA_ABSOLUTE_URI: ${{ secrets.PMA_ABSOLUTE_URI }}
  MYSQL_INIT: ${{ secrets.MYSQL_INIT }}
  MYSQL_TEST: ${{ secrets.MYSQL_TEST }}
  PHP_PARAMS: ${{ secrets.PHP_PARAMS }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}
  SERVER_PEM: ${{ secrets.SERVER_PEM }}
  TARGET: "/home/github/${{github.repository}}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create config files
        shell: bash
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$REPO, $REPO_URL, MYSQL_HOST, PMA_ABSOLUTE_URI, $TARGET" &&
          mkdir -p ./mysql/init &&
          echo "$MYSQL_INIT" > ./mysql/init/init.sql &&
          echo "$MYSQL_TEST" > ./mysql/init/test.sh &&
          mkdir -p ./nginx/conf.d &&
          echo "$PHP_PARAMS" > ./nginx/conf.d/credentials.conf &&
          mkdir -p ./nginx/ssl &&
          echo "$SERVER_KEY" > ./nginx/ssl/server.key &&
          echo "$SERVER_PEM" > ./nginx/ssl/server.pem

      - name: Copy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.DC_HOST }}
          USERNAME: ${{ secrets.DC_USER }}
          PORT: ${{ secrets.DC_PORT }}
          KEY: ${{ secrets.DC_KEY }}
          #PASSWORD: ${{ secrets.DC_PASS }}
          source: "."
          target: $TARGET

      - name: Clear config files
        shell: bash
        run: |
          rm -rf ./mysql/init &&
          rm -rf ./nginx/conf.d &&
          rm -rf ./nginx/ssl

      - name: Backup database on digitalocean
        uses: appleboy/ssh-action@master
        env:
          MYSQL_DUMPS_DIR: "${{ env.TARGET }}/mysql/backup"
        with:
          HOST: ${{ secrets.DC_HOST }}
          USERNAME: ${{ secrets.DC_USER }}
          PORT: ${{ secrets.DC_PORT }}
          KEY: ${{ secrets.DC_KEY }}
          #PASSWORD: ${{ secrets.DC_PASS }}
          envs: MYSQL_ROOT_PASSWORD, MYSQL_DUMPS_DIR, TARGET
          script: |
            echo $MYSQL_DUMPS_DIR/all_backups.sql &&
            cd $TARGET &&
            chmod -R 777 $MYSQL_DUMPS_DIR/ &&
            (docker exec mysql /usr/bin/mysqldump --all-databases -u"root" -p"$MYSQL_ROOT_PASSWORD" > "$MYSQL_DUMPS_DIR/all_backups.sql" 2>/dev/null) || true

      - name: Deploy on digitalocean
        uses: appleboy/ssh-action@master
        env:
          MYSQL_DUMPS_DIR: "${{ env.TARGET }}/mysql/backup"
        with:
          HOST: ${{ secrets.DC_HOST }}
          USERNAME: ${{ secrets.DC_USER }}
          PORT: ${{ secrets.DC_PORT }}
          KEY: ${{ secrets.DC_KEY }}
          #PASSWORD: ${{ secrets.DC_PASS }}
          envs: PMA_ABSOLUTE_URI, MYSQL_HOST, MYSQL_ROOT_PASSWORD, MYSQL_DUMPS_DIR, TARGET
          script: |
            cd $TARGET &&
            mkdir -p /var/run/mysqld &&
            chmod -R 777 /var/run/mysqld &&
            export PMA_ABSOLUTE_URI=$PMA_ABSOLUTE_URI &&
            export MYSQL_HOST=$MYSQL_HOST &&
            export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD &&
            export CURRENT_UID=$(id -u):$(id -g) &&
            docker-compose build --no-cache &&
            docker-compose rm -f -s &&
            docker-compose up --renew-anon-volumes -d

      - name: Restore database on digitalocean
        uses: appleboy/ssh-action@master
        env:
          MYSQL_DUMPS_DIR: "${{ env.TARGET }}/mysql/backup"
        with:
          HOST: ${{ secrets.DC_HOST }}
          USERNAME: ${{ secrets.DC_USER }}
          PORT: ${{ secrets.DC_PORT }}
          KEY: ${{ secrets.DC_KEY }}
          #PASSWORD: ${{ secrets.DC_PASS }}
          envs: MYSQL_ROOT_PASSWORD, MYSQL_DUMPS_DIR, TARGET
          script: |
            echo $MYSQL_DUMPS_DIR/all_backups.sql &&
            cd $TARGET &&
            (docker exec -i mysql /usr/bin/mysql -u"root" -p"$MYSQL_ROOT_PASSWORD" < "$MYSQL_DUMPS_DIR/all_backups.sql") || true

      - name: Chmod on digitalocean
        uses: appleboy/ssh-action@master
        env:
          MYSQL_DUMPS_DIR: "${{ env.TARGET }}/mysql/backup"
        with:
          HOST: ${{ secrets.DC_HOST }}
          USERNAME: ${{ secrets.DC_USER }}
          PORT: ${{ secrets.DC_PORT }}
          KEY: ${{ secrets.DC_KEY }}
          #PASSWORD: ${{ secrets.DC_PASS }}
          envs: TARGET
          script: |
            (chmod -R 777 $TARGET/) || true
